// Self-host Google Fonts used by SERRES.
// Fetches the exact woff2 files Google serves for the site's font request,
// saves them under assets/fonts/, and generates assets/fonts.css (@font-face
// rules pointing at the local files). Run: node _build/fetch-fonts.mjs
// Re-runnable: overwrites existing files.
import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const FONT_DIR = resolve(ROOT, 'assets/fonts');

// Same families/weights the site currently requests from Google Fonts.
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,400;0,500;0,600;0,700;1,600;1,700&family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600&display=swap';

// A modern Chrome UA makes Google serve woff2 (smallest, universally supported).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

async function main() {
  await mkdir(FONT_DIR, { recursive: true });
  const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error('CSS fetch failed: ' + res.status);
  let css = await res.text();

  // Split into individual @font-face blocks.
  const blocks = css.match(/@font-face\s*{[^}]*}/g) || [];
  if (!blocks.length) throw new Error('No @font-face blocks found');

  const out = [];
  const seen = new Map(); // url -> local filename (dedupe)
  let idx = 0;

  for (const block of blocks) {
    const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1] || 'font';
    const style = (block.match(/font-style:\s*([^;]+);/) || [])[1]?.trim() || 'normal';
    const weight = (block.match(/font-weight:\s*([^;]+);/) || [])[1]?.trim() || '400';
    const range = (block.match(/unicode-range:\s*([^;]+);/) || [])[1]?.trim() || '';
    const comment = (css.slice(0, css.indexOf(block)).match(/\/\*\s*([^*]+?)\s*\*\/\s*$/) || [])[1] || '';
    const url = (block.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
    if (!url) continue;

    let file = seen.get(url);
    if (!file) {
      const subset = slug(comment) || 'set';
      const wtag = weight.replace(/\s+/g, '-');
      // Stable name (family+weight+style+subset is already unique) so preload
      // references in the HTML stay valid across re-runs of this script.
      file = `${slug(family)}-${wtag}-${style}-${subset}.woff2`;
      const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
      await writeFile(resolve(FONT_DIR, file), buf);
      seen.set(url, file);
      console.log('saved', file, buf.length, 'bytes  <-', comment);
      idx++;
    }

    out.push(
      `@font-face {\n` +
        `  font-family: '${family}';\n` +
        `  font-style: ${style};\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url(fonts/${file}) format('woff2');\n` +
        (range ? `  unicode-range: ${range};\n` : '') +
        `}`
    );
  }

  const header =
    '/* SERRES self-hosted fonts — generated by _build/fetch-fonts.mjs.\n' +
    '   Barlow Condensed + DM Sans (SIL Open Font License 1.1).\n' +
    '   Self-hosted so the site never depends on Google Fonts being\n' +
    '   reachable (some networks / privacy extensions block it). */\n\n';

  await writeFile(resolve(ROOT, 'assets/fonts.css'), header + out.join('\n\n') + '\n');
  console.log('\nWrote assets/fonts.css with', out.length, '@font-face rules,', seen.size, 'woff2 files.');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
